<?php
/*
	Sedang proses diedit oleh Hadi. Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	File: qa-include/qa-lang-main.php
	Description: Language phrases commonly used throughout Q2A


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'1_answer' => '1 jawaban',
		'1_comment' => '1 komen',
		'1_day' => '1 hari',
		'1_disliked' => '1 dislike',
		'1_flag' => '1 spam',
		'1_hour' => '1 jam',
		'1_liked' => '1 like',
		'1_minute' => '1 menit',
		'1_month' => '1 bulan',
		'1_point' => '1 poin',
		'1_question' => '1 soalan',
		'1_second' => '1 detik',
		'1_tag' => '1 tag',
		'1_user' => '1 member',
		'1_view' => '1 lihat',
		'1_vote' => '1 vote',
		'1_week' => '1 minggu',
		'1_year' => '1 tahun',
		'add_category_x_favorites' => 'Tambah kategori ^ ke favoritku',
		'add_favorites' => 'Tambahkan ke favoritku',
		'add_tag_x_favorites' => 'Tambahkan tag ^ ke favoritku',
		'all_categories' => 'Semua kategori',
		'anonymous' => 'anonymous',
		'answer_edited' => 'jawaban diedit',
		'answer_reshown' => 'jawaban ditampilkan',
		'answer_selected' => 'jawaban dipilih',
		'answered' => 'dijawab',
		'answered_qs_in_x' => 'Soalan terjawab terbanyak di^',
		'answered_qs_title' => 'Pertanyaan terjawab terbanyak',
		'asked' => 'tanya',
		'asked_related_q' => 'tanya soalan yang relevan',
		'by_x' => 'dengan ^',
		'cancel_button' => 'Batal',
		'closed' => 'ditutup',
		'comment_edited' => 'komen diedit',
		'comment_moved' => 'komen dipindah',
		'comment_reshown' => 'komen ditampilkan',
		'commented' => 'dikomen',
		'date_day_min_digits' => 1, // 1 or 2
		'date_format_other_years' => '^bulan ^hari, ^tahun',
		'date_format_this_year' => '^bulan ^hari',
		'date_month_1' => 'Jan',
		'date_month_2' => 'Feb',
		'date_month_3' => 'Mar',
		'date_month_4' => 'Apr',
		'date_month_5' => 'Mei',
		'date_month_6' => 'Jun',
		'date_month_7' => 'Jul',
		'date_month_8' => 'Aug',
		'date_month_9' => 'Sep',
		'date_month_10' => 'Okt',
		'date_month_11' => 'Nov',
		'date_month_12' => 'Des',
		'date_year_digits' => 4, // 2 or 4
		'edited' => 'diedit',
		'email_error' => 'Error saat mengirim email.',
		'field_required' => 'Tolong isi sesuatu disini',
		'file_upload_limit_exceeded' => 'Besarnya file melebihi kapasitas server\'s limits',
		'general_error' => 'Error terjadi - mohon dicoba kembali.',
		'hidden' => 'sembunyikan',
		'highest_users' => 'Top skor member',
		'hot_qs_in_x' => 'Soalan Popular di ^',
		'hot_qs_title' => 'Soalan Popular',
		'image_not_read' => 'Gambar tidak dapat dibaca. Mohon unggah salah satu dari: ^',
		'image_too_big_x_pc' => 'Gambar ini terlalu besar. Mohon dikecilkan ke ^% lalu coba kembali.',
		'in_category_x' => 'di ^',
		'ip_address_x' => 'alamat IP ^',
		'logged_in_x' => 'Halo ^',
		'max_length_x' => 'Panjang maksimal ialah ^ karakter',
		'max_upload_size_x' => 'Maximum ukuran unggah ialah ^',
		'me' => 'saya',
		'meta_order' => '^what^when^where^who', // you can reorder but DO NOT translate! e.g. <answered> <15 hours ago> <in Problems> <by me (500 points)>
		'min_length_x' => 'Tolong sediakan informasi yang lebih lengkap - setidaknya ^ karakter',
		'moved' => 'pindah',
		'nav_activity' => 'Semua Aktivitas',
		'nav_admin' => 'Admin',
		'nav_ask' => 'Tanya Soalan',
		'nav_categories' => 'Kategori',
		'nav_feedback' => 'Kirim feedback',
		'nav_home' => 'Beranda',
		'nav_hot' => 'Popular!',
		'nav_login' => 'Login',
		'nav_logout' => 'Logout',
		'nav_most_answers' => 'Dijawab terbanyak',
		'nav_most_recent' => 'Yang terkini',
		'nav_most_views' => 'Dilihat terbanyak',
		'nav_most_votes' => 'Votes terbanyak',
		'nav_no_answer' => 'Belum dijawab',
		'nav_no_selected_answer' => 'Tiada jawaban diseleksi',
		'nav_no_upvoted_answer' => 'Tiada jawaban upvoted',
		'nav_qa' => 'Tanya Jawab',
		'nav_qs' => 'Soalan',
		'nav_register' => 'Daftar',
		'nav_tags' => 'Tags',
		'nav_unanswered' => 'Tidak terjawab',
		'nav_updates' => 'Updates saya',
		'nav_users' => 'Members',
		'no_active_users' => 'Tiada pengguna aktif',
		'no_answers_found' => 'Tiada jawaban ditemukan',
		'no_answers_in_x' => 'Tiada jawaban di ^',
		'no_categories_found' => 'Tiada kategori ditemukan',
		'no_category' => 'Tiada kategori',
		'no_comments_found' => 'Tiada komen ditemukan',
		'no_comments_in_x' => 'Tiada komen di ^',
		'no_questions_found' => 'Tiada soalan ditemukan',
		'no_questions_in_x' => 'Tiada soalan ditemukan di ^',
		'no_related_qs_title' => 'Tiada soalan relevan ditemukan',
		'no_results_for_x' => 'Tiada hasil ditemukan bagi ^',
		'no_tags_found' => 'Tiada tags ditemukan',
		'no_una_questions_found' => 'Tidak ditemukan pertanyaan yang tidak terjawab',
		'no_una_questions_in_x' => 'Tidak ditemukan pertanyaan yang tidak terjawab di ^',
		'no_unselected_qs_found' => 'Tiada soalan yang ditemukan tanpa jawaban yang diseleksi',
		'no_unupvoteda_qs_found' => 'Tiada soalan yang ditemukan tanpa jawaban yang diupvote',
		'page_label' => 'Halaman:',
		'page_next' => 'berikutnya',
		'page_not_found' => 'Halaman tidak ditemukan',
		'page_prev' => 'sebelumnya',
		'popular_tags' => 'Tags paling popular',
		'questions_tagged_x' => 'Soalan tag terkini^',
		'recategorized' => 'kategorikan ulang',
		'recent_activity_in_x' => 'Aktivitas terkini di ^',
		'recent_activity_title' => 'Aktivitas terkini',
		'recent_as_in_x' => 'Soalan terkini dijawab di ^',
		'recent_as_title' => 'Soalan terkini dijawab',
		'recent_cs_in_x' => 'Soalan terkini dikomen di ^',
		'recent_cs_title' => 'Soalan terkini dikomes',
		'recent_qs_as_in_x' => 'Tanya jawab terkini di ^',
		'recent_qs_as_title' => 'Tanya jawab terkini',
		'recent_qs_in_x' => 'Soalan terkini di ^',
		'recent_qs_title' => 'Soalan terkini',
		'related_qs_title' => 'Soalan yang terkait',
		'remove_favorites' => 'Hapus dari favoritku',
		'remove_x_favorites' => 'Hapus ^ dari favoritku',
		'reopened' => 'buka kembali',
		'reshown' => 'ditampilkan kembali',
		'results_for_x' => 'Hasil pencarian untuk ^',
		'retagged' => 'ditag kembali',
		'save_button' => 'Simpan Perubahan',
		'search_button' => 'Pencarian',
		'search_explanation' => 'Mohon input beberapa teks pada kotak pencarian dan dicoba kembali.',
		'search_title' => 'Hasil pencarian',
		'selected' => 'terseleksi',
		'send_button' => 'kirim',
		'since_x' => 'sejak ^',
		'suggest_ask' => 'Membantu dengan memulai ^1bertanya soalan^2.',
		'suggest_category_qs' => 'Untuk melihat lebih banyak, klik seluruh ^1soalan di kategori ini^2.',
		'suggest_qs' => 'Untuk melihat lebih banyak, klik ^1senarai penuh soalan^2.',
		'suggest_qs_tags' => 'Untuk melihat lebih banyak, klik ^1senarai penuh soalan^2 atau ^3tags popular^4.',
		'to_x' => 'ke ^',
		'unanswered_qs_in_x' => 'Soalan tanpa jawaban di ^',
		'unanswered_qs_title' => 'Soalan terkini tanpa jawaban',
		'unselected_qs_in_x' => 'Soalan terkini tanpa jawaban terseleksi di ^',
		'unselected_qs_title' => 'Soalan terkini tanpa jawaban terseleksi',
		'unupvoteda_qs_in_x' => 'Soalan tanpa jawaban upvote di ^',
		'unupvoteda_qs_title' => 'Soalan terkini tanpa jawaban upvote',
		'upload_limit' => 'Terlalu banyak unggahan - mohon coba kembali dalam 1 jam',
		'view_q_must_be_approved' => 'Akun anda harus disetujui untuk melihat halaman soalan.',
		'view_q_must_confirm' => 'Mohon ^5konfirmasi alamat email^6 untuk melihat halaman soalan.',
		'view_q_must_login' => 'Mohon ^1log in^2 atau ^3daftar^4 untuk melihat halaman soalan.',
		'viewed_qs_in_x' => 'Soalan dilihat terbanyak di ^',
		'viewed_qs_title' => 'Soalan dilihat terbanyak',
		'vote_disabled_approve' => 'Akun anda harus disetuji dahulu sebelum bisa vote',
		'vote_disabled_down' => 'Voting down cuma tersedia kepada beberapa member',
		'vote_disabled_down_approve' => 'Akun anda harus disetujui sebelum bisa vote down',
		'vote_disabled_hidden_a' => 'Anda tidak bisa vote pada jawaban yang tersembunyi.',
		'vote_disabled_hidden_q' => 'Anda tidak bisa vote pada soalan yang tersembunyi',
		'vote_disabled_level' => 'Voting cuma tersedia pada beberapa member',
		'vote_disabled_my_a' => 'Anda tidak bisa vote pada jawaban sendiri',
		'vote_disabled_my_q' => 'Anda tidak bisa vote pada soalan sendiri',
		'vote_disabled_q_page_only' => 'Mohon lihat soalan ini untuk vote',
		'vote_down_must_confirm' => 'Mohon ^5konfirmasi email anda^6 sebelum vote down.',
		'vote_down_popup' => 'Klik untuk vote down',
		'vote_limit' => 'Terlalu banyak vote yang diterima - Mohon coba kembali dalam 1 jam',
		'vote_must_confirm' => 'Mohon ^5konfirmasi email anda^6 sebelum vote.',
		'vote_must_login' => 'Mohon ^1log in^2 atau ^3daftar^4 sebelum vote.',
		'vote_not_allowed' => 'Voting pada hal ini tidak diperbolehkan',
		'vote_up_popup' => 'Klik untuk vote up',
		'voted_down_popup' => 'Anda sudah vote down - klik untuk menghapus vote',
		'voted_qs_in_x' => 'Soalan dengan vote terbanyak di ^',
		'voted_qs_title' => 'Soalan dengan vote terbanyak',
		'voted_up_popup' => 'Anda sudah vote up - klik untuk menghapus vote',
		'written' => '', // blank in English - placeholder for other languages
		'x_ago' => '^ yang lalu',
		'x_answers' => '^ jawaban',
		'x_comments' => '^ komen',
		'x_days' => '^ hari',
		'x_disliked' => '^ dislike',
		'x_flags' => '^ spam',
		'x_hours' => '^ jam',
		'x_liked' => '^ like',
		'x_minutes' => '^ menit',
		'x_months' => '^ bulan',
		'x_points' => '^ poin',
		'x_questions' => '^ soalan',
		'x_seconds' => '^ detik',
		'x_tags' => '^ tags',
		'x_users' => '^ members',
		'x_views' => '^ lihat',
		'x_votes' => '^ votes',
		'x_weeks' => '^ minggu',
		'x_years' => '^ tahun',
	);


/*
	Omit PHP closing tag to help avoid accidental output
*/
